import webbrowser
import tkinter as tk
import os
import pyautogui
from random import randint
import time
import urllib.request
pencere =tk.Tk()
canvas1 = tk.Canvas(pencere, width = 1000, height = 1000,background="black")
canvas1.pack()
pencere.title("A_HKTRFCO")
pencere.geometry("450x570")
pencere.resizable(width=False, height=False)
def Kur ():
    url = "https://finans.mynet.com/doviz/usd-dolar/"
    url2 = "https://finans.mynet.com/altin/xgld-spot-altin-tl-gr/"
    chrome_path = 'C:\Program Files\Google\Chrome\Application\chrome.exe'
    webbrowser.register('chrome', None, webbrowser.BackgroundBrowser(chrome_path))
    webbrowser.get('chrome').open_new_tab(url)
    chrome_path = 'C:\Program Files\Google\Chrome\Application\chrome.exe'
    webbrowser.register('chrome', None, webbrowser.BackgroundBrowser(chrome_path))
    webbrowser.get('chrome').open_new_tab(url2)
def TerseDöndür ():
    def TerseDöndür ():
        name = ent1.get()
        tn = str(name[::-1])
        tdk = tk.Label(text=f"{tn}",font="Arial 14 bold",fg="White",bg="black")
        canvas1.create_window(90, 270, window=tdk)
        buton.destroy()
        buton1.destroy()
        buton2.destroy()
        buton3.destroy()
        buton4.destroy()
        buton5.destroy()
        buton6.destroy()
        buton7.destroy()
        buton8.destroy()
        buton9.destroy()
        buton10.destroy()
        buton11.destroy()
    def Geri ():
        buton = tk.Button(text="HavaDurumu",width=15, height=3,command=HavaDurumu,fg='black')
        buton1 = tk.Button(text="Kur",width=15, height=3,command=Kur,fg='black')
        buton2 = tk.Button(text="AramaYapma",width=15, height=3,command=Arama,fg='black')
        buton3 = tk.Button(text="TerseDöndür",width=15, height=3,command=TerseDöndür,fg='black')
        buton4 = tk.Button(text="FFYH",width=15, height=3,command=FFYH,fg='black')
        buton5 = tk.Button(text="Çeviri",width=15, height=3,command=Çeviri,fg='black')
        buton6 = tk.Button(text="Oyunlar",width=15, height=3,command=Oyun,fg='black')
        buton7 = tk.Button(text="SaatKaç",width=15, height=3,command=SaatKaç,fg='black')
        buton8 = tk.Button(text="NFT",width=15, height=3,command=NFT,fg='black')
        buton9 = tk.Button(text="ResimÇek",width=15, height=3,command=Rsimçk,fg='black')
        buton10 = tk.Button(text="STRES",width=15, height=3,command=STRES,fg='black')
        buton11 = tk.Button(text="HESAP MAKİNESİ",width=15, height=3,command=HSP,fg='black')
        MadeByMolvess=tk.Label(text="Made By Molvess",font="Arial 12 bold",fg="blue",bg="black")
        buton.pack()
        canvas1.create_window(75, 550, window=MadeByMolvess)
        canvas1.create_window(230, 80, window=buton)
        canvas1.create_window(80, 80, window=buton1)
        canvas1.create_window(230, 150, window=buton2)
        canvas1.create_window(80, 150, window=buton3)
        canvas1.create_window(230, 220, window=buton4)
        canvas1.create_window(80, 220, window=buton5)
        canvas1.create_window(80, 290, window=buton6)
        canvas1.create_window(80, 290, window=buton6)
        canvas1.create_window(230, 290, window=buton7)
        canvas1.create_window(80, 360, window=buton8)
        canvas1.create_window(230, 360, window=buton9)
        canvas1.create_window(370, 80, window=buton10)
        canvas1.create_window(370, 150, window=buton11)
        ent1.destroy()
        AraButon.destroy()
        GERİ.destroy()
    buton.destroy()
    buton1.destroy()
    buton2.destroy()
    buton3.destroy()
    buton4.destroy()
    buton5.destroy()
    buton6.destroy()
    buton7.destroy()
    buton8.destroy()
    buton9.destroy()
    buton10.destroy()
    buton11.destroy()
    ent1 = tk.Entry(width=20)
    ent1.pack()
    canvas1.create_window(120,445,window=ent1)
    AraButon = tk.Button(text="ARA",width=12, height=2,command=TerseDöndür,fg='black')
    canvas1.create_window(270, 490, window=AraButon)
    GERİ = tk.Button(text="←",width=12, height=2,command=Geri,fg='black')
    canvas1.create_window(100, 490, window=GERİ)   
def FFYH () :
    def FFYH ():
        sayı = int(ent1.get())
        ssayı = str(sayı/100*90)
        yazı = tk.Label(text=f"Geri alıcağınız miktar :{ssayı}",font="Arial 14 bold",fg="White",bg="black")
        canvas1.create_window(150, 270, window=yazı)
    def Geri ():
        buton = tk.Button(text="HavaDurumu",width=15, height=3,command=HavaDurumu,fg='black')
        buton1 = tk.Button(text="Kur",width=15, height=3,command=Kur,fg='black')
        buton2 = tk.Button(text="AramaYapma",width=15, height=3,command=Arama,fg='black')
        buton3 = tk.Button(text="TerseDöndür",width=15, height=3,command=TerseDöndür,fg='black')
        buton4 = tk.Button(text="FFYH",width=15, height=3,command=FFYH,fg='black')
        buton5 = tk.Button(text="Çeviri",width=15, height=3,command=Çeviri,fg='black')
        buton6 = tk.Button(text="Oyunlar",width=15, height=3,command=Oyun,fg='black')
        buton7 = tk.Button(text="SaatKaç",width=15, height=3,command=SaatKaç,fg='black')
        buton8 = tk.Button(text="NFT",width=15, height=3,command=NFT,fg='black')
        buton9 = tk.Button(text="ResimÇek",width=15, height=3,command=Rsimçk,fg='black')
        buton10 = tk.Button(text="STRES",width=15, height=3,command=STRES,fg='black')
        buton11 = tk.Button(text="HESAP MAKİNESİ",width=15, height=3,command=HSP,fg='black')
        MadeByMolvess=tk.Label(text="Made By Molvess",font="Arial 12 bold",fg="blue",bg="black")
        buton.pack()
        canvas1.create_window(75, 550, window=MadeByMolvess)
        canvas1.create_window(230, 80, window=buton)
        canvas1.create_window(80, 80, window=buton1)
        canvas1.create_window(230, 150, window=buton2)
        canvas1.create_window(80, 150, window=buton3)
        canvas1.create_window(230, 220, window=buton4)
        canvas1.create_window(80, 220, window=buton5)
        canvas1.create_window(80, 290, window=buton6)
        canvas1.create_window(80, 290, window=buton6)
        canvas1.create_window(230, 290, window=buton7)
        canvas1.create_window(80, 360, window=buton8)
        canvas1.create_window(230, 360, window=buton9)
        canvas1.create_window(370, 80, window=buton10)
        canvas1.create_window(370, 150, window=buton11)
        ent1.destroy()
        HesaplaButon.destroy()
        GERİ.destroy()
    buton.destroy()
    buton1.destroy()
    buton2.destroy()
    buton3.destroy()
    buton4.destroy()
    buton5.destroy()
    buton6.destroy()
    buton7.destroy()
    buton8.destroy()
    buton9.destroy()
    buton10.destroy()
    buton11.destroy()
    ent1 = tk.Entry(width=20)
    ent1.pack()
    canvas1.create_window(120,445,window=ent1)
    HesaplaButon = tk.Button(text="ARA",width=12, height=2,command=FFYH,fg='black')
    canvas1.create_window(270, 490, window=HesaplaButon)
    GERİ = tk.Button(text="←",width=12, height=2,command=Geri,fg='black')
    canvas1.create_window(100, 490, window=GERİ)     
def Arama ():
    def Arama ():
        rgow = ent1.get()
        url = f"https://tr.wikipedia.org/wiki/{rgow}"
        url2 = f"https://www.google.com/search?q={rgow}"
        chrome_path = 'C:\Program Files\Google\Chrome\Application\chrome.exe'
        webbrowser.register('chrome', None, webbrowser.BackgroundBrowser(chrome_path))
        webbrowser.get('chrome').open_new_tab(url)
        chrome_path = 'C:\Program Files\Google\Chrome\Application\chrome.exe'
        webbrowser.register('chrome', None, webbrowser.BackgroundBrowser(chrome_path))
        webbrowser.get('chrome').open_new_tab(url2)
    def Geri ():
        buton = tk.Button(text="HavaDurumu",width=15, height=3,command=HavaDurumu,fg='black')
        buton1 = tk.Button(text="Kur",width=15, height=3,command=Kur,fg='black')
        buton2 = tk.Button(text="AramaYapma",width=15, height=3,command=Arama,fg='black')
        buton3 = tk.Button(text="TerseDöndür",width=15, height=3,command=TerseDöndür,fg='black')
        buton4 = tk.Button(text="FFYH",width=15, height=3,command=FFYH,fg='black')
        buton5 = tk.Button(text="Çeviri",width=15, height=3,command=Çeviri,fg='black')
        buton6 = tk.Button(text="Oyunlar",width=15, height=3,command=Oyun,fg='black')
        buton7 = tk.Button(text="SaatKaç",width=15, height=3,command=SaatKaç,fg='black')
        buton8 = tk.Button(text="NFT",width=15, height=3,command=NFT,fg='black')
        buton9 = tk.Button(text="ResimÇek",width=15, height=3,command=Rsimçk,fg='black')
        buton10 = tk.Button(text="STRES",width=15, height=3,command=STRES,fg='black')
        buton11 = tk.Button(text="HESAP MAKİNESİ",width=15, height=3,command=HSP,fg='black')
        MadeByMolvess=tk.Label(text="Made By Molvess",font="Arial 12 bold",fg="blue",bg="black")
        buton.pack()
        canvas1.create_window(75, 550, window=MadeByMolvess)
        canvas1.create_window(230, 80, window=buton)
        canvas1.create_window(80, 80, window=buton1)
        canvas1.create_window(230, 150, window=buton2)
        canvas1.create_window(80, 150, window=buton3)
        canvas1.create_window(230, 220, window=buton4)
        canvas1.create_window(80, 220, window=buton5)
        canvas1.create_window(80, 290, window=buton6)
        canvas1.create_window(80, 290, window=buton6)
        canvas1.create_window(230, 290, window=buton7)
        canvas1.create_window(80, 360, window=buton8)
        canvas1.create_window(230, 360, window=buton9)
        canvas1.create_window(370, 80, window=buton10)
        canvas1.create_window(370, 150, window=buton11)
        ent1.destroy()
        AraButon.destroy()
        GERİ.destroy()
    buton.destroy()
    buton1.destroy()
    buton2.destroy()
    buton3.destroy()
    buton4.destroy()
    buton5.destroy()
    buton6.destroy()
    buton7.destroy()
    buton8.destroy()
    buton9.destroy()
    buton10.destroy()
    buton11.destroy()
    ent1 = tk.Entry(width=20)
    ent1.pack()
    canvas1.create_window(120,445,window=ent1)
    AraButon = tk.Button(text="ARA",width=12, height=2,command=Arama,fg='black')
    canvas1.create_window(270, 490, window=AraButon)
    GERİ = tk.Button(text="←",width=12, height=2,command=Geri,fg='black')
    canvas1.create_window(100, 490, window=GERİ)
def HavaDurumu ():
    def HavaDurumu ():
        istn = ent1.get()
        url = f"https://www.mgm.gov.tr/tahmin/il-ve-ilceler.aspx?il={istn}"
        url2 = f"https://www.google.com.tr/search?q={istn}+hava+durumu&sxsrf=APq-WBs9IyUxZ_TxodB0-dypUFu1Nmi0vA%3A1645219369087&ei=KQ4QYufpBO-Vxc8P0Zap4Ag&ved=0ahUKEwinosngl4r2AhXvSvEDHVFLCowQ4dUDCA4&uact=5&oq=Ayd%C4%B1n+hava+durumu&gs_lcp=Cgdnd3Mtd2l6EAMyBwgjELADECcyBwgAEEcQsAMyCggAEEcQsAMQyQMyBwgAEEcQsAMyBwgAEEcQsAMyBwgAEEcQsAMyBwgAEEcQsAMyBwgAEEcQsAMyBwgAEEcQsAMyBwgAELADEENKBAhBGABKBAhGGABQAFgAYLkEaAFwAXgAgAEAiAEAkgEAmAEAyAEKwAEB&sclient=gws-wiz"
        chrome_path = 'C:\Program Files\Google\Chrome\Application\chrome.exe'
        webbrowser.register('chrome', None, webbrowser.BackgroundBrowser(chrome_path))
        webbrowser.get('chrome').open_new_tab(url)
        chrome_path = 'C:\Program Files\Google\Chrome\Application\chrome.exe'
        webbrowser.register('chrome', None, webbrowser.BackgroundBrowser(chrome_path))
        webbrowser.get('chrome').open_new_tab(url2)
    def Geri ():
        buton = tk.Button(text="HavaDurumu",width=15, height=3,command=HavaDurumu,fg='black')
        buton1 = tk.Button(text="Kur",width=15, height=3,command=Kur,fg='black')
        buton2 = tk.Button(text="AramaYapma",width=15, height=3,command=Arama,fg='black')
        buton3 = tk.Button(text="TerseDöndür",width=15, height=3,command=TerseDöndür,fg='black')
        buton4 = tk.Button(text="FFYH",width=15, height=3,command=FFYH,fg='black')
        buton5 = tk.Button(text="Çeviri",width=15, height=3,command=Çeviri,fg='black')
        buton6 = tk.Button(text="Oyunlar",width=15, height=3,command=Oyun,fg='black')
        buton7 = tk.Button(text="SaatKaç",width=15, height=3,command=SaatKaç,fg='black')
        buton8 = tk.Button(text="NFT",width=15, height=3,command=NFT,fg='black')
        buton9 = tk.Button(text="ResimÇek",width=15, height=3,command=Rsimçk,fg='black')
        buton10 = tk.Button(text="STRES",width=15, height=3,command=STRES,fg='black')
        buton11 = tk.Button(text="HESAP MAKİNESİ",width=15, height=3,command=HSP,fg='black')
        MadeByMolvess=tk.Label(text="Made By Molvess",font="Arial 12 bold",fg="blue",bg="black")
        buton.pack()
        canvas1.create_window(75, 550, window=MadeByMolvess)
        canvas1.create_window(230, 80, window=buton)
        canvas1.create_window(80, 80, window=buton1)
        canvas1.create_window(230, 150, window=buton2)
        canvas1.create_window(80, 150, window=buton3)
        canvas1.create_window(230, 220, window=buton4)
        canvas1.create_window(80, 220, window=buton5)
        canvas1.create_window(80, 290, window=buton6)
        canvas1.create_window(80, 290, window=buton6)
        canvas1.create_window(230, 290, window=buton7)
        canvas1.create_window(80, 360, window=buton8)
        canvas1.create_window(230, 360, window=buton9)
        canvas1.create_window(370, 80, window=buton10)
        canvas1.create_window(370, 150, window=buton11)
        ent1.destroy()
        AraButon.destroy()
        GERİ.destroy()
    buton.destroy()
    buton1.destroy()
    buton2.destroy()
    buton3.destroy()
    buton4.destroy()
    buton5.destroy()
    buton6.destroy()
    buton7.destroy()
    buton8.destroy()
    buton9.destroy()
    buton10.destroy()
    buton11.destroy()
    ent1 = tk.Entry(width=20)
    ent1.pack()
    canvas1.create_window(120,445,window=ent1)
    AraButon = tk.Button(text="ARA",width=12, height=2,command=HavaDurumu,fg='black')
    canvas1.create_window(270, 490, window=AraButon)
    GERİ = tk.Button(text="←",width=12, height=2,command=Geri,fg='black')
    canvas1.create_window(100, 490, window=GERİ)
def Çeviri ():
    def Çeviri():
        istn = ent1.get()
        url = f"https://www.google.com/search?q={istn}+%C3%A7eviri&sxsrf=APq-WBtDo8bEWqOLXS5qkXwqdnSn6smooA%3A1647873911425&ei=d484Ysi-GaiJxc8P5vq7YA&ved=0ahUKEwiI1v_YuNf2AhWoRPEDHWb9DgwQ4dUDCA4&uact=5&oq=died+%C3%A7eviri&gs_lcp=Cgdnd3Mtd2l6EAMyBggAEAcQHjIGCAAQBxAeMgYIABAHEB4yBggAEAcQHjIGCAAQDRAeMggIABAIEA0QHjoHCCMQsAMQJzoHCAAQRxCwAzoHCAAQsAMQQzoSCC4QxwEQ0QMQyAMQsAMQQxgBOg8ILhDUAhDIAxCwAxBDGAE6BwgjELECECdKBAhBGABKBAhGGAFQwwZY3wpg7QtoAXABeACAAZcBiAGvBJIBAzAuNJgBAKABAcgBEcABAdoBBggBEAEYCA&sclient=gws-wiz"
        chrome_path = 'C:\Program Files\Google\Chrome\Application\chrome.exe'
        webbrowser.register('chrome', None, webbrowser.BackgroundBrowser(chrome_path))
        webbrowser.get('chrome').open_new_tab(url)
    def Geri ():
        buton = tk.Button(text="HavaDurumu",width=15, height=3,command=HavaDurumu,fg='black')
        buton1 = tk.Button(text="Kur",width=15, height=3,command=Kur,fg='black')
        buton2 = tk.Button(text="AramaYapma",width=15, height=3,command=Arama,fg='black')
        buton3 = tk.Button(text="TerseDöndür",width=15, height=3,command=TerseDöndür,fg='black')
        buton4 = tk.Button(text="FFYH",width=15, height=3,command=FFYH,fg='black')
        buton5 = tk.Button(text="Çeviri",width=15, height=3,command=Çeviri,fg='black')
        buton6 = tk.Button(text="Oyunlar",width=15, height=3,command=Oyun,fg='black')
        buton7 = tk.Button(text="SaatKaç",width=15, height=3,command=SaatKaç,fg='black')
        buton8 = tk.Button(text="NFT",width=15, height=3,command=NFT,fg='black')
        buton9 = tk.Button(text="ResimÇek",width=15, height=3,command=Rsimçk,fg='black')
        buton10 = tk.Button(text="STRES",width=15, height=3,command=STRES,fg='black')
        buton11 = tk.Button(text="HESAP MAKİNESİ",width=15, height=3,command=HSP,fg='black')
        MadeByMolvess=tk.Label(text="Made By Molvess",font="Arial 12 bold",fg="blue",bg="black")
        buton.pack()
        canvas1.create_window(75, 550, window=MadeByMolvess)
        canvas1.create_window(230, 80, window=buton)
        canvas1.create_window(80, 80, window=buton1)
        canvas1.create_window(230, 150, window=buton2)
        canvas1.create_window(80, 150, window=buton3)
        canvas1.create_window(230, 220, window=buton4)
        canvas1.create_window(80, 220, window=buton5)
        canvas1.create_window(80, 290, window=buton6)
        canvas1.create_window(80, 290, window=buton6)
        canvas1.create_window(230, 290, window=buton7)
        canvas1.create_window(80, 360, window=buton8)
        canvas1.create_window(230, 360, window=buton9)
        canvas1.create_window(370, 80, window=buton10)
        canvas1.create_window(370, 150, window=buton11)
        ent1.destroy()
        ÇevirBtnn.destroy()
        GERİ.destroy()
    buton.destroy()
    buton1.destroy()
    buton2.destroy()
    buton3.destroy()
    buton4.destroy()
    buton5.destroy()
    buton6.destroy()
    buton7.destroy()
    buton8.destroy()
    buton9.destroy()
    buton10.destroy()
    buton11.destroy()
    ent1 = tk.Entry(width=20)
    ent1.pack()
    canvas1.create_window(120,445,window=ent1)
    ÇevirBtnn = tk.Button(text="Çevir",width=12, height=2,command=Çeviri,fg='black')
    canvas1.create_window(270, 490, window=ÇevirBtnn)
    GERİ = tk.Button(text="←",width=12, height=2,command=Geri,fg='black')
    canvas1.create_window(100, 490, window=GERİ)
def Oyun ():
    def valo():
        os.system("C:\\Users\\Abdullah\\Desktop\\oyunlar\\VALORANT.lnk")
    def fıfa():
        os.system("C:\\Users\\Abdullah\\Desktop\\oyunlar\\FIFAMobile.lnk")
    def lel():
        os.system("C:\\Users\\Abdullah\\Desktop\\oyunlar\\League Of Legends.lnk")
    def Geri ():
        buton = tk.Button(text="HavaDurumu",width=15, height=3,command=HavaDurumu,fg='black')
        buton1 = tk.Button(text="Kur",width=15, height=3,command=Kur,fg='black')
        buton2 = tk.Button(text="AramaYapma",width=15, height=3,command=Arama,fg='black')
        buton3 = tk.Button(text="TerseDöndür",width=15, height=3,command=TerseDöndür,fg='black')
        buton4 = tk.Button(text="FFYH",width=15, height=3,command=FFYH,fg='black')
        buton5 = tk.Button(text="Çeviri",width=15, height=3,command=Çeviri,fg='black')
        buton6 = tk.Button(text="Oyunlar",width=15, height=3,command=Oyun,fg='black')
        buton7 = tk.Button(text="SaatKaç",width=15, height=3,command=SaatKaç,fg='black')
        buton8 = tk.Button(text="NFT",width=15, height=3,command=NFT,fg='black')
        buton9 = tk.Button(text="ResimÇek",width=15, height=3,command=Rsimçk,fg='black')
        buton10 = tk.Button(text="STRES",width=15, height=3,command=STRES,fg='black')
        buton11 = tk.Button(text="HESAP MAKİNESİ",width=15, height=3,command=HSP,fg='black')
        MadeByMolvess=tk.Label(text="Made By Molvess",font="Arial 12 bold",fg="blue",bg="black")
        buton.pack()
        canvas1.create_window(75, 550, window=MadeByMolvess)
        canvas1.create_window(230, 80, window=buton)
        canvas1.create_window(80, 80, window=buton1)
        canvas1.create_window(230, 150, window=buton2)
        canvas1.create_window(80, 150, window=buton3)
        canvas1.create_window(230, 220, window=buton4)
        canvas1.create_window(80, 220, window=buton5)
        canvas1.create_window(80, 290, window=buton6)
        canvas1.create_window(80, 290, window=buton6)
        canvas1.create_window(230, 290, window=buton7)
        canvas1.create_window(80, 360, window=buton8)
        canvas1.create_window(230, 360, window=buton9)
        canvas1.create_window(370, 80, window=buton10)
        canvas1.create_window(370, 150, window=buton11)
        Valorant.destroy()
        afıfa.destroy()
        alel.destroy()
        GERİ.destroy()
    buton.destroy()
    buton1.destroy()
    buton2.destroy()
    buton3.destroy()
    buton4.destroy()
    buton5.destroy()
    buton6.destroy()
    buton7.destroy()
    buton8.destroy()
    buton9.destroy()
    buton10.destroy()
    buton11.destroy()
    Valorant = tk.Button(text="Valorant",width=12, height=2,command=valo,fg='black')
    canvas1.create_window(80, 80, window=Valorant)
    afıfa = tk.Button(text="FİFA",width=12, height=2,command=fıfa,fg='black')
    canvas1.create_window(270, 80, window=afıfa)
    alel = tk.Button(text="LOL",width=12, height=2,command=lel,fg='black')
    canvas1.create_window(80, 150, window=alel)
    GERİ = tk.Button(text="←",width=12, height=2,command=Geri,fg='black')
    canvas1.create_window(100, 490, window=GERİ)
def SaatKaç ():
    url = "https://saatkac.info.tr/"
    chrome_path = 'C:\Program Files\Google\Chrome\Application\chrome.exe'
    webbrowser.register('chrome', None, webbrowser.BackgroundBrowser(chrome_path))
    webbrowser.get('chrome').open_new_tab(url)
def NFT ():
    def Mozaik ():
        url = "https://mondrianandme.com/"
        chrome_path = 'C:\Program Files\Google\Chrome\Application\chrome.exe'
        webbrowser.register('chrome', None, webbrowser.BackgroundBrowser(chrome_path))
        webbrowser.get('chrome').open_new_tab(url)

        time.sleep(2)

        a = 1

        while a < 100:
            a += 1
            x = randint(1,1920)
            y = randint(1,1080)
            pyautogui.moveTo(x,y)
            pyautogui.click()
        time.sleep(2)
        pyautogui.rightClick()
        pyautogui.press('down')
        pyautogui.press("enter")
        time.sleep(1)
        pyautogui.press("enter")
    def CPaint ():
        url = "https://jacksonpollock.org/"
        chrome_path = 'C:\Program Files\Google\Chrome\Application\chrome.exe'
        webbrowser.register('chrome', None, webbrowser.BackgroundBrowser(chrome_path))
        webbrowser.get('chrome').open_new_tab(url)

        time.sleep(2)

        a = 1

        while a < 100:
            a += 1
            x = randint(1,1920)
            y = randint(1,1080)
            pyautogui.moveTo(x,y,1)
            pyautogui.click()
        time.sleep(2)
        pyautogui.rightClick()
        pyautogui.press('down')
        pyautogui.press("enter")
        time.sleep(1)
        pyautogui.press("enter")
    def Geri ():
        buton = tk.Button(text="HavaDurumu",width=15, height=3,command=HavaDurumu,fg='black')
        buton1 = tk.Button(text="Kur",width=15, height=3,command=Kur,fg='black')
        buton2 = tk.Button(text="AramaYapma",width=15, height=3,command=Arama,fg='black')
        buton3 = tk.Button(text="TerseDöndür",width=15, height=3,command=TerseDöndür,fg='black')
        buton4 = tk.Button(text="FFYH",width=15, height=3,command=FFYH,fg='black')
        buton5 = tk.Button(text="Çeviri",width=15, height=3,command=Çeviri,fg='black')
        buton6 = tk.Button(text="Oyunlar",width=15, height=3,command=Oyun,fg='black')
        buton7 = tk.Button(text="SaatKaç",width=15, height=3,command=SaatKaç,fg='black')
        buton8 = tk.Button(text="NFT",width=15, height=3,command=NFT,fg='black')
        buton9 = tk.Button(text="ResimÇek",width=15, height=3,command=Rsimçk,fg='black')
        buton10 = tk.Button(text="STRES",width=15, height=3,command=STRES,fg='black')
        buton11 = tk.Button(text="HESAP MAKİNESİ",width=15, height=3,command=HSP,fg='black')
        MadeByMolvess=tk.Label(text="Made By Molvess",font="Arial 12 bold",fg="blue",bg="black")
        buton.pack()
        canvas1.create_window(75, 550, window=MadeByMolvess)
        canvas1.create_window(230, 80, window=buton)
        canvas1.create_window(80, 80, window=buton1)
        canvas1.create_window(230, 150, window=buton2)
        canvas1.create_window(80, 150, window=buton3)
        canvas1.create_window(230, 220, window=buton4)
        canvas1.create_window(80, 220, window=buton5)
        canvas1.create_window(80, 290, window=buton6)
        canvas1.create_window(80, 290, window=buton6)
        canvas1.create_window(230, 290, window=buton7)
        canvas1.create_window(80, 360, window=buton8)
        canvas1.create_window(230, 360, window=buton9)
        canvas1.create_window(370, 80, window=buton10)
        canvas1.create_window(370, 150, window=buton11)
        Mozik.destroy()
        CPaintt.destroy()
        GERİ.destroy()
    buton.destroy()
    buton1.destroy()
    buton2.destroy()
    buton3.destroy()
    buton4.destroy()
    buton5.destroy()
    buton6.destroy()
    buton7.destroy()
    buton8.destroy()
    buton9.destroy()
    buton10.destroy()
    buton11.destroy()
    Mozik = tk.Button(text="Mozaik",width=12, height=2,command=Mozaik,fg='black')
    canvas1.create_window(80, 80, window=Mozik)
    CPaintt = tk.Button(text="CPaint",width=12, height=2,command=CPaint,fg='black')
    canvas1.create_window(270, 80, window=CPaintt)
    GERİ = tk.Button(text="←",width=12, height=2,command=Geri,fg='black')
    canvas1.create_window(100, 490, window=GERİ)
def Rsimçk ():
    def Rsimçk ():
        current_folder = os.getcwd()
        images_folder = current_folder + os.sep + "FOTOLAR"
        if not os.path.isdir(images_folder):
            os.mkdir(images_folder)

        n = int(ent1.get())
        url = "https://source.unsplash.com/random"

        for i in range(1, n+1):
            filename = images_folder + os.sep + f"Foto{i}" + ".png"
            urllib.request.urlretrieve(url, filename)
    def Geri ():
        buton = tk.Button(text="HavaDurumu",width=15, height=3,command=HavaDurumu,fg='black')
        buton1 = tk.Button(text="Kur",width=15, height=3,command=Kur,fg='black')
        buton2 = tk.Button(text="AramaYapma",width=15, height=3,command=Arama,fg='black')
        buton3 = tk.Button(text="TerseDöndür",width=15, height=3,command=TerseDöndür,fg='black')
        buton4 = tk.Button(text="FFYH",width=15, height=3,command=FFYH,fg='black')
        buton5 = tk.Button(text="Çeviri",width=15, height=3,command=Çeviri,fg='black')
        buton6 = tk.Button(text="Oyunlar",width=15, height=3,command=Oyun,fg='black')
        buton7 = tk.Button(text="SaatKaç",width=15, height=3,command=SaatKaç,fg='black')
        buton8 = tk.Button(text="NFT",width=15, height=3,command=NFT,fg='black')
        buton9 = tk.Button(text="ResimÇek",width=15, height=3,command=Rsimçk,fg='black')
        buton10 = tk.Button(text="STRES",width=15, height=3,command=STRES,fg='black')
        buton11 = tk.Button(text="HESAP MAKİNESİ",width=15, height=3,command=HSP,fg='black')
        MadeByMolvess=tk.Label(text="Made By Molvess",font="Arial 12 bold",fg="blue",bg="black")
        buton.pack()
        canvas1.create_window(75, 550, window=MadeByMolvess)
        canvas1.create_window(230, 80, window=buton)
        canvas1.create_window(80, 80, window=buton1)
        canvas1.create_window(230, 150, window=buton2)
        canvas1.create_window(80, 150, window=buton3)
        canvas1.create_window(230, 220, window=buton4)
        canvas1.create_window(80, 220, window=buton5)
        canvas1.create_window(80, 290, window=buton6)
        canvas1.create_window(80, 290, window=buton6)
        canvas1.create_window(230, 290, window=buton7)
        canvas1.create_window(80, 360, window=buton8)
        canvas1.create_window(230, 360, window=buton9)
        canvas1.create_window(370, 80, window=buton10)
        canvas1.create_window(370, 150, window=buton11)
        Bİndir.destroy()
        yazı.destroy()
        GERİ.destroy()
        ent1.destroy()
    buton.destroy()
    buton1.destroy()
    buton2.destroy()
    buton3.destroy()
    buton4.destroy()
    buton5.destroy()
    buton6.destroy()
    buton7.destroy()
    buton8.destroy()
    buton9.destroy()
    buton10.destroy()
    buton11.destroy()
    ent1 = tk.Entry(width=20)
    ent1.pack()
    canvas1.create_window(120,445,window=ent1)
    Bİndir = tk.Button(text="Bİndir",width=12, height=2,command=Rsimçk,fg='black')
    canvas1.create_window(270, 490, window=Bİndir)
    yazı = tk.Label(text="İndirmek istediğiniz \n görsel saysı :",font="Arial 16 bold",fg="White",bg="black")
    canvas1.create_window(120, 370, window=yazı)
    GERİ = tk.Button(text="←",width=12, height=2,command=Geri,fg='black')
    canvas1.create_window(100, 490, window=GERİ)
def STRES ():
    def BAĞIR ():
        url = "https://screamintothevoid.com/"
        chrome_path = 'C:\Program Files\Google\Chrome\Application\chrome.exe'
        webbrowser.register('chrome', None, webbrowser.BackgroundBrowser(chrome_path))
        webbrowser.get('chrome').open_new_tab(url)
    def Geri ():
        buton = tk.Button(text="HavaDurumu",width=15, height=3,command=HavaDurumu,fg='black')
        buton1 = tk.Button(text="Kur",width=15, height=3,command=Kur,fg='black')
        buton2 = tk.Button(text="AramaYapma",width=15, height=3,command=Arama,fg='black')
        buton3 = tk.Button(text="TerseDöndür",width=15, height=3,command=TerseDöndür,fg='black')
        buton4 = tk.Button(text="FFYH",width=15, height=3,command=FFYH,fg='black')
        buton5 = tk.Button(text="Çeviri",width=15, height=3,command=Çeviri,fg='black')
        buton6 = tk.Button(text="Oyunlar",width=15, height=3,command=Oyun,fg='black')
        buton7 = tk.Button(text="SaatKaç",width=15, height=3,command=SaatKaç,fg='black')
        buton8 = tk.Button(text="NFT",width=15, height=3,command=NFT,fg='black')
        buton9 = tk.Button(text="ResimÇek",width=15, height=3,command=Rsimçk,fg='black')
        buton10 = tk.Button(text="STRES",width=15, height=3,command=STRES,fg='black')
        buton11 = tk.Button(text="HESAP MAKİNESİ",width=15, height=3,command=HSP,fg='black')
        MadeByMolvess=tk.Label(text="Made By Molvess",font="Arial 12 bold",fg="blue",bg="black")
        buton.pack()
        canvas1.create_window(75, 550, window=MadeByMolvess)
        canvas1.create_window(230, 80, window=buton)
        canvas1.create_window(80, 80, window=buton1)
        canvas1.create_window(230, 150, window=buton2)
        canvas1.create_window(80, 150, window=buton3)
        canvas1.create_window(230, 220, window=buton4)
        canvas1.create_window(80, 220, window=buton5)
        canvas1.create_window(80, 290, window=buton6)
        canvas1.create_window(80, 290, window=buton6)
        canvas1.create_window(230, 290, window=buton7)
        canvas1.create_window(80, 360, window=buton8)
        canvas1.create_window(230, 360, window=buton9)
        canvas1.create_window(370, 80, window=buton10)
        canvas1.create_window(370, 150, window=buton11)
        BBAĞIR.destroy()
        GERİ.destroy()
    buton.destroy()
    buton1.destroy()
    buton2.destroy()
    buton3.destroy()
    buton4.destroy()
    buton5.destroy()
    buton6.destroy()
    buton7.destroy()
    buton8.destroy()
    buton9.destroy()
    buton10.destroy()
    buton11.destroy()
    BBAĞIR = tk.Button(text="BAĞIR",width=12, height=2,command=BAĞIR,fg='black')
    canvas1.create_window(80, 80, window=BBAĞIR)
    GERİ = tk.Button(text="←",width=12, height=2,command=Geri,fg='black')
    canvas1.create_window(100, 490, window=GERİ)
def HSP ():
    os.system("C:\\Windows\\system32\\calc.exe")

buton = tk.Button(text="HavaDurumu",width=15, height=3,command=HavaDurumu,fg='black')
buton1 = tk.Button(text="Kur",width=15, height=3,command=Kur,fg='black')
buton2 = tk.Button(text="AramaYapma",width=15, height=3,command=Arama,fg='black')
buton3 = tk.Button(text="TerseDöndür",width=15, height=3,command=TerseDöndür,fg='black')
buton4 = tk.Button(text="FFYH",width=15, height=3,command=FFYH,fg='black')
buton5 = tk.Button(text="Çeviri",width=15, height=3,command=Çeviri,fg='black')
buton6 = tk.Button(text="Oyunlar",width=15, height=3,command=Oyun,fg='black')
buton7 = tk.Button(text="SaatKaç",width=15, height=3,command=SaatKaç,fg='black')
buton8 = tk.Button(text="NFT",width=15, height=3,command=NFT,fg='black')
buton9 = tk.Button(text="ResimÇek",width=15, height=3,command=Rsimçk,fg='black')
buton10 = tk.Button(text="STRES",width=15, height=3,command=STRES,fg='black')
buton11 = tk.Button(text="HESAP MAKİNESİ",width=15, height=3,command=HSP,fg='black')
MadeByMolvess=tk.Label(text="Made By Molvess",font="Arial 12 bold",fg="blue",bg="black")
buton.pack()
canvas1.create_window(75, 550, window=MadeByMolvess)
canvas1.create_window(230, 80, window=buton)
canvas1.create_window(80, 80, window=buton1)
canvas1.create_window(230, 150, window=buton2)
canvas1.create_window(80, 150, window=buton3)
canvas1.create_window(230, 220, window=buton4)
canvas1.create_window(80, 220, window=buton5)
canvas1.create_window(80, 290, window=buton6)
canvas1.create_window(80, 290, window=buton6)
canvas1.create_window(230, 290, window=buton7)
canvas1.create_window(80, 360, window=buton8)
canvas1.create_window(230, 360, window=buton9)
canvas1.create_window(370, 80, window=buton10)
canvas1.create_window(370, 150, window=buton11)
pencere.mainloop()